apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: "--enable-helm"
  statusbadge.enabled: "true"
  url: "https://argocd.vdgtconsultancy.be"
  oidc.config: |
    name: PocketID
    issuer: https://id.terpstra.tech
    clientId: 05f1a740-d0f0-4387-b63f-afd6bb323681
    clientSecret: $oidc.pocketid.clientSecret
    redirectUrl: https://argocd.vdgtconsultancy.be/auth/callback
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
