apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  application.namespaces: "platform-apps, sandbox-apps, shared-apps, restricted-apps, public-apps"
  server.insecure: "true"