apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: "--enable-helm"
  statusbadge.enabled: "true"
  url: "https://argocd.vdgtconsultancy.be"
  oidc.config: |
    name: PocketID
    issuer: https://id.terpstra.tech
    clientId: 3f355ade-c0c2-4489-b0b5-1dfa55b9419d
    clientSecret: $oidc.pocketid.clientSecret
    redirectUrl: https://argocd.vdgtconsultancy.be/auth/callback
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
