apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  source:
    repoURL: https://github.com/jterpstra1/argocd-setup.git
    path: argocd-setup/overlays/vdgt-k3s/cluster-issuers
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
