apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  destination:
    name: in-cluster
    namespace: nginx-ingress
  project: default
  source:
    repoURL: https://github.com/jterpstra1/argocd-setup.git
    path: argocd-setup/overlays/vdgt-k3s/ingress-nginx
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/ports/0/nodePort
    - /spec/ports/1/nodePort
