apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: "--enable-helm"
  statusbadge.enabled: "true"
  resource.exclusions: |
    - apiGroups:
        - batch
      kinds:
        - Job
      clusters:
        - "*"
      names:
        - ingress-nginx-admission-patch
  url: "https://argocd.terpstra.tech"
  oidc.config: |
    name: PocketID
    issuer: https://id.terpstra.tech
    clientId: a0c109e7-b60d-4baf-980a-a044cb26f3fe
    clientSecret: $oidc.pocketid.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  policy.csv: |
    p, role:admin, *, *, *, allow
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, certificates, get, *, allow
    p, role:readonly, logs, get, *, allow
    g, argocd_admin, role:admin
    g, argocd_readonly, role:readonly
