apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: pocketid-client-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: pocketid-client-secret
        property: clientSecret
