apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
stringData:
  oidc.pocketid.clientSecret: "pocketid-client-secret"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-secret
spec:
  itemPath: "vaults/n7ix2o34u5dwbwfrjl65cypkni/items/pocketid-client-secret"
