apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    metallb.universe.tf/allow-shared-ip: "argocd"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.11.20
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server