apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: AppProject
  patch: |-
    - op: replace
      path: /metadata/name
      value: public-apps
    - op: replace
      path: /spec/description
      value: Project for public-facing applications
    - op: replace
      path: /spec/destinations/0/name
      value: public-apps
    - op: add
      path: /spec/sourceNamespaces
      value: ["public-apps"]
    - op: add
      path: /spec/roles
      value:
        - name: admin
          description: Admin role with full access
          policies:
            - p, proj:public-apps:admin, applications, *, public-apps/*, allow
          groups:
            - argocd-admins
