apiVersion: v1
kind: Namespace
metadata:
  name: platform-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: shared-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: restricted-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: public-apps