apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-ingress

helmCharts:
- name: nginx-ingress
  repo: https://helm.nginx.com/stable
  version: 2.4.4
  releaseName: nginx-ingress
  namespace: nginx-ingress
  valuesInline:
    controller:
      config:
        use-http2: "true"                    # enable HTTP/2
        proxy-buffer-size: "16k"
      reportIngressStatus:
        enableLeaderElection: false
      service:
        annotations:
          load-balancer.hetzner.cloud/name: vdgt-k3s-nginx
          load-balancer.hetzner.cloud/location: nbg1
          load-balancer.hetzner.cloud/use-private-ip: "false"
