apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-ingress

resources:
- github.com/nginx/kubernetes-ingress//deployments?ref=v5.3.4

patches:
- path: service-patch.yaml
